name: Dockerizing Subsbase Notification Center Backend

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - backend/**

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Setup
    outputs:
      short-sha: ${{steps.short-sha.outputs.short-sha}}
      image-name: ${{steps.image-name.outputs.image-name}}
    steps:
      - id: image-name
        run: echo "::set-output name=image-name::notification-center-api"
      - id: short-sha
        run: echo "::set-output name=short-sha::$(echo '${{ github.sha }}' | cut -c 1-7)"

  build_and_push_image:
    runs-on: ubuntu-latest
    name: Build and Push Image
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Image meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/subsbase/${{ needs.setup.outputs.image-name }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            ${{ needs.setup.outputs.short-sha }}
            latest

      - name: Log in to ghcr
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to ghcr
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}