name: Dockerizing Subsbase Notification Center Frontend

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - frontend/**

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Setup
    outputs:
      short-sha: ${{steps.short-sha.outputs.short-sha}}
      container-name: ${{steps.container-name.outputs.container-name}}
      image-name: ${{steps.image-name.outputs.image-name}}
    steps:
      - id: container-name
        run: echo "::set-output name=container-name::notification-center"
      - id: short-sha
        run: echo "::set-output name=short-sha::$(echo '${{ github.sha }}' | cut -c 1-7)"
      - id: image-name
        run: echo "::set-output name=image-name::ghcr.io/subsbase/${{ steps.container-name.outputs.container-name }}:${{ steps.short-sha.outputs.short-sha }}"
  build_and_push_image:
    runs-on: ubuntu-latest
    name: Build and Push Image
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to ghcr
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ needs.setup.outputs.image-name }}